name: openfootball
version: 0.1.0
config-version: 2

profile: openfootball_duckdb

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: []

models:
  openfootball:
    +materialized: view   # staging as views: fast, simple
    stg:
      +schema: stg        # logical schema name inside DuckDB
